export const ROUTES = {
  HOME: "/",
  EXPLORER: "/explorer",
  CACHE: "/cache",
  DEBLOAT: "/debloat",
  SERVICES: "/services",
  REGISTRY: "/registry",
  RESTORE: "/restore",
  AUDIT: "/audit",
  SETTINGS: "/settings",
  PROCESSES: "/processes",
  STARTUP: "/startup",
  DISK: "/disk",
  PRIVACY: "/privacy",
} as const;
